---
title: "Correlation test and modeling with Naver Shopping Insight data(NSI) & KMA observations"
output: html_document
params:
  date: !r Sys.Date()
  print_code: FALSE
  start_date: "2017-08-01"
  end_date: "2020-07-31"
---
<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = params$print_code)
knitr::opts_chunk$set(fig.width = 12, fig.height = 5, fig.align = "center")
options(width = 160)
options(max.print = 10000)
options(crayon.enabled = FALSE)
options(dplyr.summarise.inform = FALSE)

library(dplyr)
library(ggplot2)
library(here)
library(jsonlite)
library(knitr)

source(paste0(here(), "/src/get_kma_obs.R"))

# KMA data preparation
region <- "Seoul"
invisible(capture.output(get_clean_raw_KMA(region)))
invisible(capture.output(add_base_derived_features(region)))

kma_df <- KMA_DF
for (feat_name in kma_feat_names) {
  if (feat_name %in% colnames(kma_df[[region]])) {
    next
  }
  kma_df[[region]][[feat_name]] <- derive_kma_feature(region, feat_name)
}
assign("KMA_DF", kma_df, envir = .GlobalEnv)
rm(kma_df)

kma_subset <- get_KMA_subset(region, 2017, 8, 2020, 7)
reset_KMA_data()

# NSI data preparation
res_json <- read_json(
  paste0(here(), "/data/Naver_Shopping_Insight/20170801_20200731.json"))
res_list <- list()
for (name in names(res_json[["results"]][[1]][["data"]][[1]])) {
  res_list[[name]] <- unlist(lapply(res_json[["results"]][[1]][["data"]],
                                    function(x) { x[[name]] }))
}
nsi_all <- data.frame(res_list)
nsi_mo <- nsi_all[which(nsi_all$group == "mo"), ]
rownames(nsi_mo) <- NULL
nsi_pc <- nsi_all[which(nsi_all$group == "pc"), ]
rownames(nsi_pc) <- NULL

TOP_N_Feats <- 10
```

## * Naver Shopping Category: Blouse/Shirts (50000804)

# [EDA for NSI]

``` {r EDA_NSI}
cat("[NSI/Mobile] statistical summary:\n")
print(summary(nsi_mo$ratio))

cat("[NSI/PC] statistical summary:\n")
print(summary(nsi_pc$ratio))

boxplot(ratio ~ group, data = nsi_all, col = sample(rainbow(2)),
        xlab = "Device category", ylab = "User click ratio")

tmp_df <- nsi_all
tmp_df[which(!(endsWith(tmp_df$period, suffix = "-01") |
                 endsWith(tmp_df$period, suffix = "-15"))), "period"] <- ""
p <- ggplot(data = tmp_df, aes(x = period, y = ratio, group = group)) +
  geom_line(aes(colour = group)) + labs(colour = "Decive category") +
  xlab("Daily period") + ylab("User click ratio") +
  theme(axis.text.x = element_text(angle = 90))
print(p)
rm(tmp_df)
```

# [Correlation between KMA & NSI]

## Region: Seoul

``` {r Corr_Seoul}
common_dates <- intersect(intersect(nsi_mo$period, nsi_pc$period),
                          kma_subset$date)
nsi_mo <- nsi_mo[which(nsi_mo$period %in% common_dates), ]
nsi_pc <- nsi_pc[which(nsi_pc$period %in% common_dates), ]
kma_subset <- kma_subset[which(kma_subset$date %in% common_dates), ]

cat("dim(kma_subset):", dim(kma_subset), "\n")
cat("kma_subset head & tail:\n")
print(head(kma_subset[, c(1:3, (ncol(kma_subset) - 5):ncol(kma_subset))]))
print(tail(kma_subset[, c(1:3, (ncol(kma_subset) - 5):ncol(kma_subset))]))
cat("dim(nsi_mo):", dim(nsi_mo), "\n")
cat("nsi_mo head & tail:\n")
print(head(nsi_mo))
print(tail(nsi_mo))
cat("dim(nsi_pc):", dim(nsi_pc), "\n")
cat("nsi_pc head & tail:\n")
print(head(nsi_pc))
print(tail(nsi_pc))

corr_df <- data.frame(KMA_FEAT = kma_feat_names,
                      MO = rep(0.0, length(kma_feat_names)),
                      PC = rep(0.0, length(kma_feat_names)))
cat("[Correlation] between KMA & (NSI mobile, pc)\n")
for (feat_name in kma_feat_names) {
  corr_df[which(corr_df$KMA_FEAT == feat_name), "MO"] <-
    cor(kma_subset[[feat_name]], nsi_mo$ratio)
  corr_df[which(corr_df$KMA_FEAT == feat_name), "PC"] <-
    cor(kma_subset[[feat_name]], nsi_pc$ratio)
}
print(corr_df)

cat("[Statistical Summary] for correlation of NSI mobile\n")
valid_corrs_mo <- corr_df[which(!is.na(corr_df$MO)), "MO"]
print(summary(valid_corrs_mo))
cat("[Statistical Summary] for correlation of NSI pc\n")
valid_corrs_pc <- corr_df[which(!is.na(corr_df$PC)), "PC"]
print(summary(valid_corrs_pc))

cat("******************** multiple linear regression with top", TOP_N_Feats,
    "most correlated features ********************\n")
cat("[NSI mobile] ====================\n")
corr_mo <- corr_df[which(!is.na(corr_df$MO)), c("KMA_FEAT", "MO")]
corr_mo$ABS <- abs(corr_mo$MO)
corr_mo <- corr_mo[order(-corr_mo$ABS), ]
top_mo_feats <- head(corr_mo$KMA_FEAT, n = TOP_N_Feats)
cat("Top", TOP_N_Feats, "most correlated features for NSI mobile:\n")
print(top_mo_feats)
fit_df <- nsi_mo[, c("period", "ratio")]
fit_df <- fit_df %>%
  inner_join(kma_subset[, c("date", top_mo_feats)], by = c("period" = "date"))
fit_df <- fit_df[complete.cases(fit_df), ]
cat("(after inner-join & filtering) dim(fit_df):", dim(fit_df), "\n")
print(head(fit_df))
print(tail(fit_df))
frmla <- as.formula(paste(colnames(fit_df)[2],
                          paste(colnames(fit_df)[3:ncol(fit_df)], sep = "",
                                collapse = " + "),
                          sep = " ~ "))
# print(frmla)
fit <- lm(frmla , data = fit_df)
summary(fit)  # show results

cat("[NSI pc] ====================\n")
corr_pc <- corr_df[which(!is.na(corr_df$PC)), c("KMA_FEAT", "PC")]
corr_pc$ABS <- abs(corr_pc$PC)
corr_pc <- corr_pc[order(-corr_pc$ABS), ]
top_pc_feats <- head(corr_pc$KMA_FEAT, n = TOP_N_Feats)
cat("Top", TOP_N_Feats, "most correlated features for NSI pc:\n")
print(top_pc_feats)
fit_df <- nsi_pc[, c("period", "ratio")]
fit_df <- fit_df %>%
  inner_join(kma_subset[, c("date", top_pc_feats)], by = c("period" = "date"))
fit_df <- fit_df[complete.cases(fit_df), ]
cat("(after inner-join & filtering) dim(fit_df):", dim(fit_df), "\n")
print(head(fit_df))
print(tail(fit_df))
frmla <- as.formula(paste(colnames(fit_df)[2],
                          paste(colnames(fit_df)[3:ncol(fit_df)], sep = "",
                                collapse = " + "),
                          sep = " ~ "))
# print(frmla)
fit <- lm(frmla , data = fit_df)
summary(fit)  # show results
```
